#!/bin/bash

# Dynamicznie wykryj nazwę użytkownika
USER=$(whoami)

# Ścieżka do urządzenia
USB_MOUNT="CLONEZILLA_DATA"

# Sprawdzenie, czy katalog 'grubzilla-skrypty' istnieje na partycji EXT4
if [ ! -d "/media/$USER/$USB_MOUNT/grubzilla-scripts" ]; then
    echo "Catalog '/media/$USER/$USB_MOUNT/grubzilla-scripts' does not exist."
    exit 1
fi

# Przejdź do katalogu 'grubzilla-skrypty'
cd "/media/$USER/$USB_MOUNT/grubzilla-scripts" || { echo "Error: Unable to navigate to the directory."; exit 1; }

# Uruchom skrypt konfigurator_OS.sh
sudo bash configurator_OS.sh

